### ISSUE TITLE
Create an achievement section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#105]
Changes are to be made in index.html, styles.html and index.js files.

### Achievement  Section should contain:
Title: Accomplishment.
- 500+ Members
- 25+ Events
-  10+ Mentorship Provided
Background should be white, and colour should be matching with the theme
___

### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
![website-design-preview-73973](https://user-images.githubusercontent.com/104223990/194276616-9b36df7d-13de-48ab-9f34-5fc7f187c3c5.jpg)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by JASKIRAT11011** [comment]
i want to contribute on this issue , can you please assign me this

**Comment by spike-spiegel-21** [comment]
I have experience with the Bootstrap library. I will be able to create this section. Requesting to assign me this task.

**Comment by JASKIRAT11011** [comment]
@girlscript-asansol i have a made a PR for a achievement section, can u confirm please

**Comment by JASKIRAT11011** [comment]
@girlscript-asansol @jay-io

**Comment by thatsuman** [comment]
I want to work on this

**Comment by jay-io** [comment]
@thatsuman  Go to #114 for samples.
