### ISSUE TITLE
Past Event Changes

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#113]
- make the past event section in the mobile view one after the other. Currently it is like 3 cards vertically showing but make it one card at a time
- the transition is not smooth enough make the carousel transition smooth.
### Present past event section
![Screenshot from 2022-10-06 18-51-09](https://user-images.githubusercontent.com/104223990/194324322-a0d65499-11a0-42d6-91b2-26677b46dc63.png)
### how it should look
![Screenshot from 2022-10-06 18-54-58](https://user-images.githubusercontent.com/104223990/194324821-cdeacbd8-c2a0-48a0-961b-aac2ee448a83.png)

**Comment by debjitpurohit** [comment]
assign me on this issue

**Comment by subashpaul** [comment]
Raised PR. plz check it
