### ISSUE TITLE
Will be adding favicon for website.

### ISSUE THREAD

**Issue by Anikalp1** [gsasansol/GirlScript-Asansol#125]
1.  [ ] Will be adding favicon for girlscript asansol logo.

![Screenshot (105)](https://user-images.githubusercontent.com/96365444/194480876-f0599c0c-d256-4d90-b6f9-80b64a9305c1.png)

**Comment by jay-io** [comment]
Please go through the contribution rules in [`README.md`](https://github.com/gsasansol/GirlScript-Asansol/blob/main/README.md).
