### ISSUE TITLE
Apply Typed.js in the header title

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#127]
- add a typed.js effect
- use your creativity

**Comment by keelus** [comment]
Hello. Could I work on this? Under hacktoberfest 2022

**Comment by Sanket2004** [comment]
I want to work on this.
you can assign it to me.
Thank you.

**Comment by KeneePatel** [comment]
Can I pick up on this, as it has been more than 11 days

**Comment by KeneePatel** [comment]
I will be able to get it done in a day

**Comment by KeneePatel** [comment]
Feel free to assign me on this if it's okay @jay-io or @girlscript-asansol

**Comment by jay-io** [comment]
Go ahead! I'm working on an animated banner which will prolly take time. We can have yours in the meantime. Can you try to make it look better? Without the image maybe? Look for a few inspirations if possible.
