### ISSUE TITLE
Revamp the Navbar

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#128]
- change font-weight (in the ancor tag) don't make it bold
- Add social links in noti bar
- change hover effect on anchor tags

**Comment by SabujGolui** [comment]
Assign it to me. I'll be more than pleased to assist.

**Comment by srijoy-paul** [comment]
@girlscript-asansol Can you assign this to me? I would like to work on this

**Comment by jay-io** [comment]
@SabujGolui @SabujGolui This issue has already been assigned. Wait for newer issues or suggest your own features and fixes on our Discord forum. I'll recommend the latter.

**Comment by jay-io** [comment]
@theanimator20 Oh no, this is about the navbar on the top. You're up!

**Comment by theanimator20** [comment]
Okay so basically u'll need to  change the font add social links and add hover effect.?

**Comment by theanimator20** [comment]
Can i get ur social links to add

**Comment by theanimator20** [comment]
Can i get the social links or should i put dummy text

**Comment by jay-io** [comment]
Try improving the hover effect too. Design is actually very subjective so it's better if you can work closely with us. Consider creating a thread on our Discord forum to get started.

**Comment by theanimator20** [comment]
Okk

**Comment by jay-io** [comment]
@theanimator20 Could you add a new item in the navbar with an animated dropdown titled "Follow us" and list the social links (GitHub, LinkedIn, Twitter, Instagram & Discord) under that? I think it'll be more convenient. Do this for the widescreen layout. For mobile view, consider adding the above social links (only) individually as hrefs on icons.

**Comment by theanimator20** [comment]
Ok seems okay with me and for mobile view I'll add the icons vertically at right corner(scrollable)

**Comment by jay-io** [comment]
@theanimator20 Sounds good!

**Comment by soumali28** [comment]
@theanimator20 whats the update?

**Comment by jay-io** [comment]
@theanimator20 try white (with 70% opacity) default font style instead of the brown. Hovering makes the font 100% opaque and hence, bright white. You may also do away with the red underline, replace it will a fade-in-fade-out thin white underline.

**Comment by theanimator20** [comment]
@jay-io i have solved the issue please go through it
