### ISSUE TITLE
Fix the noti-bar cross, and some more changes

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#129]
- The noti bar has a cross button which overlays in the website.(for mobile view) Fix the position of it.
![Screenshot from 2022-10-07 13-24-17](https://user-images.githubusercontent.com/104223990/194502866-37fd35e1-b49c-48ac-b653-d9fb568d216e.png)
- Add some padding at the bottom of  the h1 of the accomplishment(mobile view).
- Decrease the padding (in the mobile view) between the accomplishment section and faq section
- Add a gradient line (small) after the past event section, accomplishment and faq.

**Comment by debjitpurohit** [comment]
Assing me o this issue.
