### ISSUE TITLE
Create the About Us section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#13]
Changes are to be made in index.html, styles.html and index.js files.

### About Us Section should contain:
- Image: Click [here](https://media-exp2.licdn.com/dms/image/C4E0BAQGnt6Z0DtV3qg/company-logo_200_200/0/1650306023304?e=2147483647&v=beta&t=SjqqiNj2VZMqm9RDLHMak5q8n4iO9Fv3JBz7PHErReo) for the image link
- Title: About Us.
- Content: GirlScript Organization is a non-profit company registered under the government of India on 2nd June 2017. GirlScript aims to empower people and especially underrepresented groups in the field of technology.
GirlScript Asansol's mission is to create opportunity, learning, growth and diversity in technology academia and industry.
- Social Media Button : [link](https://gsa.bio.link/)

___

- Title 2: Our Programs
- Content: Encourage people to learn to program and make them capable of writing a simple computer program to building a complex system. Empower people by providing an opportunity to showcase their technical skills. 
- Card Section: 
         - Career Guidance
         - Open Source
         - Workshops and Sessions

### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
![Screenshot from 2022-09-30 20-18-38](https://user-images.githubusercontent.com/104223990/193297601-c27542c9-4bc9-4e41-8a76-d91b30691cec.png)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by souravaniket** [comment]
Please assign this to me

**Comment by Subhangi0707** [comment]
I want to work on this issue under hacktoberfest 2022
THANKS!!!

**Comment by jay-io** [comment]
@souravaniket If you would rather like to consider a less cluttered solution, you can add your html/js components in separate folders (with appropriate feature naming) inside [`components/[feature]`](https://github.com/gsasansol/GirlScript-Asansol/tree/main/components) instead of the `index.html` in the root. We'll have it merged later into the main HTML file (we'll put up a separate issue). The contents of `[feature]` can be: `index.html`, `styles.css`, `index.js` with the body of `index.html` wrapping the component.

**Comment by Debdeep1** [comment]
@souravaniket any update about the work?

**Comment by RathoreAbhiii** [comment]
I would be willing to work on this issue if there are no updates soon! @girlscript-asansol Could you maybe assign it to me if needed? Thanks!

**Comment by Debdeep1** [comment]
> I would be willing to work on this issue if there are no updates soon! @girlscript-asansol Could you maybe assign it to me if needed? Thanks!

Thanks for letting us know.

**Comment by girlscript-asansol** [comment]
@souravaniket any updates kindly let us know by today else we have to reassign it.

**Comment by RathoreAbhiii** [comment]
> Please assign this to me

Please look for any other issues as I am working on this. Thanks!

**Comment by RathoreAbhiii** [comment]
> > > Please assign this to me
> > 
> > 
> > Please look for any other issues as I am working on this. Thanks!
> 
> I can work on this, kindly assign me this issue.

Yes, @girlscript-asansol. Could you please assign this issue to him as I have completed a similar issue in a different repository, as a result l, I am unassigning this issue from me. Hope you understand. Thanks!

**Comment by RathoreAbhiii** [comment]
> > > > Please assign this to me
> > > 
> > > 
> > > Please look for any other issues as I am working on this. Thanks!
> > 
> > 
> > I can work on this, kindly assign me this issue.
> 
> Yes, @girlscript-asansol. Could you please assign this issue to him as I have completed a similar issue in a different repository, as a result l, I am unassigning this issue from me. Hope you understand. Thanks!

@nub-rin will be carrying forward the rest of my work, that's why I am asking to assign this issue to him.

**Comment by jay-io** [comment]
@RathoreAbhiii Okay, sure.

**Comment by yogesh-9999** [comment]
hey @JASKIRAT11011  Please assign this to me

**Comment by jay-io** [comment]
@nub-rin Any updates? Please respond, or we'll have to reassign. We have other contributors willing to work on this portion.

**Comment by nub-rin** [comment]
> @nub-rin Any updates? Please respond, or we'll have to reassign. We have other contributors willing to work on this portion.

Hey, sorry for the delay. I will be creating a pr in like 3 hrs from now. Will post an update screenshot for revision in around an hour.

**Comment by jay-io** [comment]
@nub-rin Thank you. We're actually rooting for this one to complete our first milestone. I hope you understand.

**Comment by nub-rin** [comment]
@jay-io should the about us have a separate page or integrated in index.html?

**Comment by nub-rin** [comment]
> @jay-io should the about us have a separate page or integrated in index.html?

Nevermind found it.

**Comment by nub-rin** [comment]
@jay-io This is the upper part, the background can be anything (currently its white cause i dont find any image that dose not conflict with the svg above it. The card is work in progress (~15-30 mins). Lmk you opinion.
![unknown](https://user-images.githubusercontent.com/82444564/194702342-64d26342-2777-4423-9b37-2364b0805de4.png)

**Comment by jay-io** [comment]
Cards feel like an overdoing. You may just arrange the paragraphs alternately one after the other on either side of the centre. Like in this sample below. The next paragraph could be towards the left and illustration to the right. For now, put the GSA logo in place of the illustrations.

![Screenshot from 2022-10-08 15-53-18](https://user-images.githubusercontent.com/55305804/194702862-405d326f-6935-4995-a7c6-b29e2c2fc349.png)

PS. I don't know why the weird phantom text overlay is here

**Comment by nub-rin** [comment]
> Cards feel like an overdoing. You may just arrange the paragraphs alternately one after the other on either side of the centre. Like in this sample below. The next paragraph could be towards the left and illustration to the right. For now, put the GSA logo in place of the illustrations.
> 
> ![Screenshot from 2022-10-08 15-53-18](https://user-images.githubusercontent.com/55305804/194702862-405d326f-6935-4995-a7c6-b29e2c2fc349.png)
> 
> PS. I don't know why the weird phantom text overlay is here

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/82444564/194705130-2239b3fa-d706-4c69-8233-8ad11ded210b.png">
 
How about this?

**Comment by soumali28** [comment]
> > Cards feel like an overdoing. You may just arrange the paragraphs alternately one after the other on either side of the centre. Like in this sample below. The next paragraph could be towards the left and illustration to the right. For now, put the GSA logo in place of the illustrations.
> > ![Screenshot from 2022-10-08 15-53-18](https://user-images.githubusercontent.com/55305804/194702862-405d326f-6935-4995-a7c6-b29e2c2fc349.png)
> > PS. I don't know why the weird phantom text overlay is here
> 
> <img alt="image" width="1680" src="https://user-images.githubusercontent.com/82444564/194705130-2239b3fa-d706-4c69-8233-8ad11ded210b.png">
> 
> How about this?

Instead of our services it will be our programs and remove the box shawdow (you can give that in the pics tho) and change the images. Ill share some illustration.

**Comment by nub-rin** [comment]
Alright!

**Comment by jay-io** [comment]
Looks good! Can you add a bit more padding between two horizontal sections? Also, bring the heading and the content a tad bit closer. You could also increase the `font-weight` for the section heading text.

**Comment by jay-io** [comment]
For now, you may just add two subsequent sections so that someone can easily append along any new content with your original work. And we'll raise a no-code issue for the content-writing. You may use *Lorem Ipsum*.

**Comment by nub-rin** [comment]
Alright!!
