### ISSUE TITLE
Add animations to the Accomplishments Section

### ISSUE THREAD

**Issue by soustab10** [gsasansol/GirlScript-Asansol#134]
Change the static accomplishments section to animated (Figures start from 0 to the number) giving the site a more dynamic look.
![image](https://user-images.githubusercontent.com/95632583/194639540-c886c9e8-36cb-46ce-b83d-45385a5ea452.png)

The dark mode toggle does not change to moon icon when switched to dark mode.

If approved, I would like to work on these issues.

**Comment by Vic-Dev001** [comment]
Please assign this to me.  

Under the Hacktoberfest

**Comment by VedantBandeJain** [comment]
please assign this issue to me  I understood the thing u expect.

**Comment by girlscript-asansol** [comment]
@soustab10 Thanks for raising this issue. We'll assign it too you but from the next time before raising the issue plz discuss it in our discord forum.

**Comment by jay-io** [comment]
@soustab10 I think the mobile view layout for the accomplishment cards is irregular. Could you please do something about it? No worries if you cannot. We'll create a new issue.

**Comment by soumali28** [comment]
@soustab10 Whats the update? Kindly respond by today else we have to reassign it
