### ISSUE TITLE
Dark mode icon 

### ISSUE THREAD

**Issue by AnkitaMalik22** [gsasansol/GirlScript-Asansol#138]
Page is changing to dark mode but the icon is not changing .
- show dark mode icon when page is on light mode 
- show light mode icon when page is on dark mode

![Screenshot_20221008-082017.png](https://user-images.githubusercontent.com/80139836/194684598-bc5b9d39-58ff-414a-ae87-b700a53329e8.png)

I would love to do it,please assign me!

**Comment by girlscript-asansol** [comment]
@AnkitaMalik22 Thanks for raising this issue. But I believe someone already working on similar issue so for the time being we have to close it. But you can suggest more custom issue on our discord server.
