### ISSUE TITLE
Create the Past Event Section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#14]
Changes are to be made in index.html, styles.html and index.js files.

### Past Event Section should contain:
- Title: Our Past Events.
- Check the linkedIn page to find the events or join discord : [link of LinkedIn](https://www.linkedin.com/company/gsasansol/)

___
### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
![Screenshot from 2022-09-30 20-36-02](https://user-images.githubusercontent.com/104223990/193300003-5971a097-d828-41e7-9613-ed0e0019c675.png)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by jay-io** [comment]
@Sahilbal If you would rather like to consider a less cluttered solution, you can add your html/js components in separate folders (with appropriate feature naming) inside [`components/[feature]`](https://github.com/gsasansol/GirlScript-Asansol/tree/main/components) instead of the `index.html` in the root. We'll have it merged later into the main HTML file (we'll put up a separate issue). The contents of `[feature]` can be: `index.html`, `styles.css`, `index.js` with the body of `index.html` wrapping the component.

**Comment by Sahilbal** [comment]
I am having doubt what exactly your past events include . I am mentioning below some of the events I got from your linkedin page . please guide me if this is all or am i missing something.
past events of girlscript-asanol:
1. Careerscript episode(1&2)
2. portfolio competetion
3. Mother's day poster making competetion

**Comment by Sahilbal** [comment]
@jay-io I am having doubt what exactly your past events include . I am mentioning below some of the events I got from your linkedin page . please guide me if this is all or am i missing something.
past events of girlscript-asanol:

1.Careerscript episode(1&2)
2.portfolio competetion
3.Mother's day poster making competetion

**Comment by jay-io** [comment]
@Sahilbal Yes that's all we've had, since our chapter is very new (5months+). You can continue with these.
Make sure the cards contain:
1. Event poster
2. Event title
3. Brief event description (~30 words)

**Comment by Sahilbal** [comment]
> @Sahilbal Yes that's all we've had, since our chapter is very new (5months+). You can continue with these. Make sure the cards contain:
> 
> 1. Event poster
> 2. Event title
> 3. Brief event description (~30 words)

okay. understood. thank you.

**Comment by girlscript-asansol** [comment]
@Sahilbal Whats the update?

**Comment by Sahilbal** [comment]
finishing it up.. I'll submit the PR by night.
