### ISSUE TITLE
UI and UX Changes

### ISSUE THREAD

**Issue by Morbius00** [gsasansol/GirlScript-Asansol#140]
<img src="https://img.shields.io/badge/hacktoberfest-2022-blueviolet" alt="Hacktober Badge"/>

# UI and UX Changes
I just check out your website and I found that your website needs a little spice up of UI and UX .
so, please assigned me for it I hope I will not disappoint you.

**Comment by girlscript-asansol** [comment]
@Morbius00 Can you discuss the changes with us in our discord forum and elaborate what changes you will do then we'll create an issue for you.
