### ISSUE TITLE
UI and UX  changes

### ISSUE THREAD

**Issue by Morbius00** [gsasansol/GirlScript-Asansol#141]
<img src="https://img.shields.io/badge/hacktoberfest-2022-blueviolet" alt="Hacktober Badge"/>

# UI and UX  changes

Hey guys I just checked your website and find out that you guys need a little spice up of UI and UX changes
So, please assigned me for it  I hope that I will not disappoint you guys.
Regards,

**Comment by girlscript-asansol** [comment]
@Morbius00 Can you discuss the changes with us in our discord forum and elaborate what changes you will do then we'll create an issue for you.

**Comment by Morbius00** [comment]
> @Morbius00 Can you discuss the changes with us in our discord forum and elaborate what changes you will do then we'll create an issue for you.

 Yea Sure 
# Here you can see the heading is collapsing and the cards also looks a little bit boring
SOL: fixing the issue and add a little bit hover animation cards
![Screenshot 2022-10-08 111848](https://user-images.githubusercontent.com/102956488/194691316-e7522350-6e75-4fb6-a643-e224efbd1546.png)
# the unwanted break  line
![Screenshot 2022-10-08 111914](https://user-images.githubusercontent.com/102956488/194691324-c37e7041-831b-4852-b7a4-7dfdff71732b.png)
## Make the Girl Script tile a little bit attractive  and use a more attractive colour gradient of orange and yellow color
![Screenshot 2022-10-08 111944](https://user-images.githubusercontent.com/102956488/194691329-350ad3dd-5873-41fa-b8ae-237d426e7a11.png)
and some more changes if required.

**Comment by girlscript-asansol** [comment]
@Morbius00 
- for the accomplishment cards dont add the any animation its already created and someone is working on it.
- You can add hover effect though on the cards
- fix the line break and the accomplishment padding (this only happens in the 4k resolution in other view points its perfect)
- the navbar issue is already there and someone is fixing it so no need for the navbar changes.

**Comment by Morbius00** [comment]
ok thanks for the assigned

**Comment by Morbius00** [comment]
> @Morbius00
> 
> * for the accomplishment cards dont add the any animation its already created and someone is working on it.
> * You can add hover effect though on the cards
> * fix the line break and the accomplishment padding (this only happens in the 4k resolution in other view points its perfect)
> * the navbar issue is already there and someone is fixing it so no need for the navbar changes.
> * also the lines which are there before each section we want that to be under the headings and decrese the width of it too
>   Assigning it to you

hey @girlscript-asansol  many of you scss files and bootstarap files are missing in this repo.
thats why cant able to fix the issues

**Comment by jay-io** [comment]
@Morbius00 All good?

**Comment by Morbius00** [comment]
> @Morbius00 All good?

yea good required changes made ready to pr
