### ISSUE TITLE
Create the Resource Page

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#142]
Create a new file in Resources folder named  resource.html, resource.css and resource.js.

### Resource page should contain:
- Navbar (already made)
- Cards for the resources (you can find the resources under components>articles) 
- custom Scroll bar(already made)
- Instead of Roadmaps as title give it Resources and Roadmaps
- Link the resource.html file to the resoruces in the navbar section.
- On clicking on the explore more button it should open the blogsCard.html
___

### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
![Screenshot from 2022-10-08 11-53-58](https://user-images.githubusercontent.com/104223990/194692708-2ca2e89b-cfb1-40a0-a299-ef66853a6571.png)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by SatyajeetShinde** [comment]
Can you please assign me the task.

**Comment by Vedant003** [comment]
Hello @girlscript-asansol can you please assign me the task ?

**Comment by soumali28** [comment]
@SatyajeetShinde Whats the update?

**Comment by navaneethmanoj** [comment]
Hi, can you please assign me this issue?

**Comment by jay-io** [comment]
@navaneethmanoj any updates? Are you on this yet?

**Comment by navaneethmanoj** [comment]
The UI is completed. I have a few questions. Where in the discord server can I discuss it?

**Comment by jay-io** [comment]
@navaneethmanoj you can write it out in #october-general. We'll get back to you as soon as possible.
