### ISSUE TITLE
Create a 'Contact Us' form

### ISSUE THREAD

**Issue by Ritu01-git** [gsasansol/GirlScript-Asansol#148]
The contact us button is not working, I can create this part:

> Please provide your email and name then submit button

This will send us the issue faced by the user.

**Comment by soumali28** [comment]
@Ritu01-git the contact us page is not yet merged. And already an issue is there for creating the form. If you want to create custom issues you can join our discord forum to discuss the changes with the maintainers and then we shall create the issues for you.
