### ISSUE TITLE
Dark mode for contact us section.

### ISSUE THREAD

**Issue by Debdeep1** [gsasansol/GirlScript-Asansol#155]
- Apply dark mode in contact us section.

![WhatsApp Image 2022-10-08 at 19 01 38](https://user-images.githubusercontent.com/89895057/194710246-40fb3cf7-59a9-474d-9f16-df4baa0c6b8a.jpeg)

**Comment by jsvigneshkanna** [comment]
Hey 👋, @Debdeep1 Please assign this issue to me. I would like to contribute the code.
Appreciate that

**Comment by girlscript-asansol** [comment]
@jsvigneshkanna yeah dark mode is already done but the contact us section you see the heading the the sphere it doesn't fetch the dark mode you have to fix that

**Comment by Aman-Singh-Kushwaha** [comment]
I wanted to work on this as per in discord thread

**Comment by jsvigneshkanna** [comment]
> I wanted to work on this as per in discord thread

Hi @Aman-Singh-Kushwaha , I have already started working on this

**Comment by jsvigneshkanna** [comment]
Hi @girlscript-asansol , I have raised a new PR for this issue
#162 

Please add label `hacktoberfest-accepted`, so that I can keep track of all my contributions this month

**Comment by Debdeep1** [comment]
> Hi @girlscript-asansol , I have raised a new PR for this issue #162
> 
> Please add label `hacktoberfest-accepted`, so that I can keep track of all my contributions this month

Hey  can you please add some screenshots to show what changes did you make...m having a bit confusion. Screenshots of the ui changes that u made for dark mode.
Thanks.

**Comment by Debdeep1** [comment]
Done
