### ISSUE TITLE
Carousel design Fixes in Mobile View

### ISSUE THREAD

**Issue by vaibhava17** [gsasansol/GirlScript-Asansol#156]
Hello !
I have looked into your website and found that the carousel section on mobile is busted.
![image](https://user-images.githubusercontent.com/65801959/194710897-8cb1a278-0366-449d-a5dc-e03493425c29.png)
I can help in fixing that just assign me this issue.
Thanks

**Comment by jay-io** [comment]
Worse, looks wasted to me

**Comment by jay-io** [comment]
Can you also fix the stretched posters that's making it look weirder?

**Comment by vaibhava17** [comment]
@girlscript-asansol noted!

**Comment by soumali28** [comment]
@vaibhava17 whats the update?

**Comment by vaibhava17** [comment]
@soumali28 today I was busy I will submit tomorrow in the evening
