### ISSUE TITLE
Oveflow fix in the about section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#157]
- Fix the overflow which is there in the about us section
- decrease the font size a bit
- give margin and padding to it

**Comment by Aman-Singh-Kushwaha** [comment]
I want to work on this

**Comment by qudus2019** [comment]
I want to work on this

**Comment by Aman-Singh-Kushwaha** [comment]
@qudus2019 i am working on it

**Comment by qudus2019** [comment]
> @qudus2019 i am working on it

Okay, weldone
