### ISSUE TITLE
Revamp "Past Events"

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#158]
- background image is weird, makes the light/dark theme flow inconsistent (can someone do anything better here?)
- a better implementation of carousel. Something cleaner, like [this](https://www.youtube.com/watch?v=qOO6lVMhmGc).
- the event posters may be compressed to help with faster page load-ups
- please remove the background

Assigned to `yosaami#4099` from forums.

**Comment by yosaami** [comment]
I would like to contribute to this issue.

**Comment by soumali28** [comment]
@yosaami Whats the update?

**Comment by yosaami** [comment]
I'll try to complete it by the end of the day

**Comment by soumali28** [comment]
@yosaami Whats the update??

**Comment by jay-io** [comment]
@yosaami Sorry, it's been a while. I'll have to reassign this one.

**Comment by KeneePatel** [comment]
I would like to work on this issue if it's fine, please assign me on this.
