### ISSUE TITLE
Compose an original writeup Document/Roadmap on Web Development 

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#16]
- Write it in either Google Docs or on Ms Word.
- Make sure to add flowcharts/images.
-  Share the article link in PR.

**Comment by si-ddhant** [comment]
Hi!! I can work on this documentation. Can you assign it to me??

**Comment by crsdvaibhav** [comment]
Hey can I also start working on this issue, I would Notion for a proper roadmap!

**Comment by Nisha213-mar** [comment]
Can you Assign this work to me

**Comment by Santushti26** [comment]
can you assign this work to me?

**Comment by Debdeep1** [comment]
@si-ddhant any update?

**Comment by si-ddhant** [comment]
> @si-ddhant any update?

Yes!! Just finishing it up. Gonna submit the PR by night.

**Comment by si-ddhant** [comment]
> @si-ddhant any update?

i am having issues converting markdown file into utf-8 string
