### ISSUE TITLE
Make the logo redirecting

### ISSUE THREAD

**Issue by Snehil0603** [gsasansol/GirlScript-Asansol#165]
* The logo in navbar should take you to home page. Would you assign me this issue?

**Comment by jay-io** [comment]
@Snehil0603 We have a similar issue that I've been assigned to PR for and I've already added the hyperlink. If you'd like to contribute to this repository any further, please consider starting discussion threads in our Discord forums. Also, read the contribution guidelines for this repository in the project README.
