### ISSUE TITLE
Compose an original writeup Document/Roadmap on Data Structures

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#17]
- Write it in either Google Docs or on Ms Word.
- Make sure to add flowcharts/images.
-  Share the article link in PR.

**Comment by krn563** [comment]
Hi I am interested can u please assign it to me.

**Comment by Nisha213-mar** [comment]
Please Assign this Work to me

**Comment by Debdeep1** [comment]
@krn563 any update?

**Comment by JASKIRAT11011** [comment]
@jay-io can u please assign me this

**Comment by Ritu01-git** [comment]
@soumali28 I want to work in this issue

**Comment by soumali28** [comment]
@JASKIRAT11011 whats the update?

**Comment by JASKIRAT11011** [comment]
I was little busy in college work ,can you give more clarity on how many pages doc u want

**Comment by joyjeetcoding** [comment]
Hii, I am interested in this..... can I also do this ?.....

**Comment by jay-io** [comment]
@JASKIRAT11011 I'm sorry we have to reassign this. We got a few milestones to reach on time. I hope you understand.

**Comment by joyjeetcoding** [comment]
Hii @jay-io Can you assign me this ?

**Comment by AdityaShaw1** [comment]
is this issue open ?

**Comment by jay-io** [comment]
@AdityaShaw1 You can watch a couple of videos on Cryptography and pen down what you understood. This issue is already assigned but the one on Cryptography remains.

**Comment by AdityaShaw1** [comment]
Yes pls assign me
