### ISSUE TITLE
Proofread the project README & CONTRIBUTING.md

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#175]
Remove typos, grammatical errors & reformat

**Comment by eddybruv** [comment]
can I work on this?

**Comment by jay-io** [comment]
@eddybruv Sure, go ahead!

**Comment by eddybruv** [comment]
Great!

**Comment by IncredibleZuess** [comment]
Hi! @jay-io can I help out too?

**Comment by jay-io** [comment]
@IncredibleZuess Hey there!
You may take up #178, thank you.

**Comment by amitkumar-y** [comment]
Hi @jay-io ,
Please let me know if there are any other documentation changes that I can assist with.

**Comment by jay-io** [comment]
@amitkumar-y I will reopen this issue to have you do the same. I can see a few minor spelling errors that went unnoticed, especially in the README.

**Comment by Saket2** [comment]
I would like to contribute.

**Comment by jay-io** [comment]
@Saket2 Sorry, we've run out of proofreading issues for now :(
