### ISSUE TITLE
Contact Us form send button not working

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#176]
- The send button in the contact us is not working
- we can have a mailto for now and send the responses to : girlscriptasansol@gmail.com

**Comment by capooods** [comment]
Can work on this

**Comment by jay-io** [comment]
@capooods sure!
[mailto:girlscriptasansol@gmail.com](mailto:girlscriptasansol@gmail.com)

**Comment by capooods** [comment]
Pull request can be located here: #180
