### ISSUE TITLE
Modify the our programs section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#177]
- Remove the logo and add cards
Title: Our Programs
Content: Encourage people to learn to program and make them capable of writing a simple computer program to building a complex system. Empower people by providing an opportunity to showcase their technical skills.
Card Section:
- Career Guidance
- Open Source
- Workshops and Sessions
___

### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
![Screenshot from 2022-10-10 14-47-44](https://user-images.githubusercontent.com/104223990/194834716-5ccacd75-610c-4ef3-9348-c0c34de15c8b.png)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by Karmakarsaurab** [comment]
@girlscript-asansol i want to contribute in your project.so can you please assign me this

**Comment by Prathyusha20a** [comment]
Assign me this issue,I would like to add cards

**Comment by jay-io** [comment]
@Karmakarsaurab You're up for this one. Please go through the contribution guidelines in our README if you haven't yet.

@Prathyusha20a We're assigning to the earliest commenters. If you'd like to contribute further, consider joining our Discord forum to discuss your own issues with the maintainers and have them assigned to you after approval, in short notice.

**Comment by jay-io** [comment]
@Karmakarsaurab any updates?

**Comment by Adhetya** [comment]
@girlscript-asansol, I would be interested to work on this issue. Please assign this issue to me. Also, mentioning the deadline to submit a PR would be much appreciated.

**Comment by AdityaShaw1** [comment]
Do u guys need only design ??

**Comment by AdityaShaw1** [comment]
if yes then pls assign me to this issue..

**Comment by soumali28** [comment]
> @girlscript-asansol, I would be interested to work on this issue. Please assign this issue to me. Also, mentioning the deadline to submit a PR would be much appreciated.

Submit it within 3-4 days will be appreaciated.

**Comment by savi001** [comment]
I am interesed to work on ,
can u assign this to me ?

**Comment by jay-io** [comment]
@Adhetya are you working on this one?

**Comment by Adhetya** [comment]
@jay-io Yes, I am. Will try to submit a PR by today. If not, definitely tomorrow.
