### ISSUE TITLE
Proofread articles

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#178]
They can be found in [`components/articles`](https://github.com/gsasansol/GirlScript-Asansol/tree/main/components/articles).

Tasks:
- rectify typos,
- grammatical errors, 
- bad punctuation, and 
- reformat.

Make changes ***in the markdown files only***.

**Comment by IncredibleZuess** [comment]
Hi @jay-io! I'll definitely take this one

**Comment by jay-io** [comment]
@IncredibleZuess Go ahead!

**Comment by IncredibleZuess** [comment]
Should I submit the changes as one pr or multiple prs @jay-io?

**Comment by jay-io** [comment]
@IncredibleZuess We're accepting one Hacktoberfest PR per issue. So it has to be one. I understand it might be lot to review. So no rush. You may take your time.

**Comment by jay-io** [comment]
@IncredibleZuess We'll also add your name (from [`CONTRIBUTORS`](https://github.com/gsasansol/GirlScript-Asansol/blob/main/CONTRIBUTORS)) as a reviewer in our blog pages.

**Comment by IncredibleZuess** [comment]
@jay-io Alright! 

I'll get on it then! :)
