### ISSUE TITLE
Compose an original writeup Document/Roadmap on Artificial Intelligence and Machine Learning

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#18]
- Write it in either Google Docs or on Ms Word.
- Make sure to add flowcharts/images.
-  Share the article link in PR.

**Comment by skar07** [comment]
Hello! Would love to work on this. Please assign this under hacktoberfest to me.

**Comment by arpitasen20** [comment]
I want to work on this.

**Comment by shrutityagi4102** [comment]
Hey @girlscript-asansol  can i take this issue ?
