### ISSUE TITLE
Prevent empty contact-us form submission and missing hrefs in the navigation bar

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#182]
What the title says.

**Comment by capooods** [comment]
I can work on this one also.

**Comment by vivek0033** [comment]
Pull request for this issue : #181

**Comment by jay-io** [comment]
#181 merged

**Comment by jay-io** [comment]
@capooods **vivek0033** is a beginner and he already had a PR on this one, so I had to assign him instead. This issue was one of his introductions to open-source. I hope you understand.

**Comment by capooods** [comment]
No problem, @jay-io ! Good job @vivek0033
