### ISSUE TITLE
Create an Express.js instance using node that will listen (@POST) for json contact-us form data

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#184]
API endpoint will be:
```kotlin
@POST("$baseUrl/cweb/contactus")
```
This data will then we handled by the discord client and relayed back to the GSA server. Join Discord to discuss implementation with the maintainers.

Discord bot: #185

**Comment by TilteD24** [comment]
Hello I would like to work on this issue

**Comment by jay-io** [comment]
@TilteD24 Kindly join the Discord forums and keep us updated in this [thread](https://discord.com/channels/963463889692020827/1029331634861903913).

**Comment by TilteD24** [comment]
Can you please link the discord channel I can't seem to find it
