### ISSUE TITLE
Create a discord.js bot client to send contact-us form data to GSA server's channel

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#185]
Data is received by the Express.js instance running alongwith.
Text channel ID: `1029085447344881686`

Join the Discord server to discuss implementation with maintainers.

Express server: #184

**Comment by drealmap** [comment]
I would like to work on this

**Comment by jay-io** [comment]
@drealmap Please read the contribution guidelines and try to finish within the stipulated time. Thank you for contributing!
