### ISSUE TITLE
Dummy Text in About Us and Our Programs section

### ISSUE THREAD

**Issue by Sumedh-byte** [gsasansol/GirlScript-Asansol#187]
There is dummy text on both About Us and Our Programs section. I can edit them if any content is provided.

**Comment by jay-io** [comment]
We actually don't have a lot of content as of now. You may comment on if you are interested in writing content for us though, for those sections you mentioned. They kinda need to be around 150 words in length each enumerating all that we've done and all that we plan to do in the future. You might also have to work closely with our core team. Let me know if you're interested.
