### ISSUE TITLE
Compose an original writeup Document/Roadmap on Blockchain

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#19]
- Write it in either Google Docs or on Ms Word.
- Make sure to add flowcharts/images.
-  Share the article link in PR.

**Comment by arpitasen20** [comment]
I would love to work on this.

**Comment by Nisha213-mar** [comment]
I want to do this Work

**Comment by jay-io** [comment]
@Nisha213-mar Are you up for this?

**Comment by debjitpurohit** [comment]
Can u assign me on this issue?

**Comment by jay-io** [comment]
@debjitpurohit Sure.

**Comment by debjitpurohit** [comment]
Thank you @jay-io
