### ISSUE TITLE
Compose an original writeup Document/Roadmap on DevOps.

### ISSUE THREAD

**Issue by Debdeep1** [gsasansol/GirlScript-Asansol#192]
### What's on your mind?

- Write it in either Google Docs or on Ms Word.
- Make sure to add flowcharts/images.
- Share the article link in PR.

### Contribution Guidelines

- [X] I have gone through the contribution guidelines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joyjeetcoding** [comment]
Hii.. I am interested to do this ....Can you assign me this ?...It's my first time contributing in open source

**Comment by jay-io** [comment]
@joyjeetcoding Welcome to open-source! Refer to [this](https://github.com/gsasansol/GirlScript-Asansol/issues/21#issuecomment-1264372470) thread to know how we receive article submissions. Hit us up on Discord if you face any issues. See how [others have done it](https://github.com/gsasansol/GirlScript-Asansol/tree/main/components/articles).
