### ISSUE TITLE
Compose an original writeup Document/Roadmap on Cryptography

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#20]
- Write it in either Google Docs or on Ms Word.
- Make sure to add flowcharts/images.
-  Share the article link in PR.

**Comment by arpitasen20** [comment]
I want to work on this.

**Comment by Nisha213-mar** [comment]
Please Assign this work to me

**Comment by girlscript-asansol** [comment]
@arpitasen20 whats the update?

**Comment by arpitasen20** [comment]
> @arpitasen20 whats the update?

Will be uploading today...almost done

**Comment by JASKIRAT11011** [comment]
@jay-io can u please assign me this

**Comment by soumali28** [comment]
@JASKIRAT11011 what's the update?

**Comment by JASKIRAT11011** [comment]
I am getting little busy in college activities and other ,I may need some time to work on this 
But prior to that ,I have the content of dsa roadmap just need to integrate it properly

**Comment by joyjeetcoding** [comment]
Hii ......Can you assign me this ?

**Comment by pratyusha0710** [comment]
Hey, can you assign me this??

**Comment by AdityaShaw1** [comment]
can u pls assign me
