### ISSUE TITLE
Modify the about us section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#201]
Changes are to be made in index.html, styles.html and index.js files.

### About Us Section should contain:
- Image: Change the image from the logo to an illustration like [this](https://i.ibb.co/SVsVj3s/undraw-Software-engineer-re-tnjc.png) or any other suitable.
- Content:  Change the lorem to "GirlScript Organization is a non-profit company registered under the government of India on 2nd June 2017. GirlScript aims to empower people and especially underrepresented groups in the field of technology.
GirlScript Asansol's mission is to create opportunity, learning, growth and diversity in technology academia and industry."
- Social Media Button : change the hover effect and border radius (make it like the header join us button)

___

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by savi001** [comment]
I am interested to work on it ,
can u assign this to me .

**Comment by NabhiA** [comment]
I would like to work on this issue. 
Can you assign it to me

**Comment by tanyaa-arora** [comment]
Hi @girlscript-asansol I'd like to do this. Kindly assign me this issue

**Comment by Eazyisreal** [comment]
Kindly assign this task to me @girlscript-asansol
