### ISSUE TITLE
[Feature]: enhanced scale,dimensions and ui

### ISSUE THREAD

**Issue by nikcoder01** [gsasansol/GirlScript-Asansol#202]
### Contact Details

nikhil896160@gmail.com

### What's on your mind?

want to make fonts and alignment more appropriate in proportion and appealing in look, please assign tis to me

### Contribution Guidelines

- [X] I have gone through the contribution guidelines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jay-io** [comment]
@nikcoder01 Can you specify which sections you'd like to improve? We're currently looking for contributions which have a well defined scope. Consider opening a new issue targeting exactly what you'd like to focus on first. Say, "Enforcing a font style (font-face and size) standard throughout the repository"
We kinda need help with this one.
