### ISSUE TITLE
[Bug]: Mobile View of dropdown menu is not centered

### ISSUE THREAD

**Issue by danieleavolio** [gsasansol/GirlScript-Asansol#207]
### Contact Details

daniele.avolio14@gmail.com

### What happened?

A bug happened!
I noticed that the dropdown menu is not centered.
![image](https://i.imgur.com/0A6ISgK.png)

### Version

0.1.0rc (Default)

### What browsers are you seeing the problem on?

Chrome

### Contribution Guidelines

- [X] I have gone through the contribution guidelines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soumali28** [comment]
@danieleavolio Thanks for creating this issue but I think this issue is already resolved/ You can check our discord and suggest some custom issues if you want too.
