### ISSUE TITLE
Compose an original writeup Document/Roadmap on DBMS (brief introduction to SQL/NoSQL)

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#21]
- Write it in either Google Docs or on Ms Word.
- Make sure to add flowcharts/images.
- Share the article link in PR.

**Comment by utkarsh006** [comment]
@jay-io Kindly assign me this issue.

**Comment by jay-io** [comment]
@utkarsh006 sure, go ahead!

**Comment by utkarsh006** [comment]
@jay-io What files I would be adding to Github? Should I write the article in README.md?

**Comment by jay-io** [comment]
@utkarsh006 You need to save the article as a JSON in this format and place it in the path [`components/articles`](https://github.com/gsasansol/GirlScript-Asansol/tree/main/components/articles).
```json
{
  "title": "TITLE GOES HERE",
  "body": "MARKDOWN ARTICLE FORMATTED AS UTF-8 STRING",
  "author": "FIRSTNAME LASTNAME",
  "email": "AUTHOR EMAIL",
  "date": "DATE OF PULL REQUEST & FORMAT AS <DD/MM/YYYY>",
  "references": [
    "LIST",
    "OF",
    "REFERENCES"
  ]
}
```

Use Node's `fs` module to generate your UTF8 string from the Markdown article:
```js
const fs = require('fs');

fs.writeFileSync(
  'D:\path\to\output.txt', 
  JSON.stringify(
    fs.readFileSync('C:\path\to\markdown\article.md')
      .toString('utf8')
  )
);
```
For queries, visit our Discord.

**Comment by utkarsh006** [comment]
Kindly check my article [LINK](https://docs.google.com/document/d/17q_QEJ_e1Oy_seW9OHScb3zLk0kbTfXiupClbzJLLN8/edit?usp=sharing)

**Comment by debjitpurohit** [comment]
I am a hacktoberfest 2022 participant. Please assing this issue to me.

**Comment by jay-io** [comment]
@debjitpurohit Go ahead.
