### ISSUE TITLE
[Bug]: Lorem text in "Our Programs" section

### ISSUE THREAD

**Issue by MashyBasker** [gsasansol/GirlScript-Asansol#212]
### Contact Details

basumaharshi10@gmail.com

### What happened?

The `Our Programs` section on the main page of the site contains just Lorem text. 
I'd be happy to work on this issue.
![girlscript](https://user-images.githubusercontent.com/84385565/196359175-216927e8-698a-41b3-ac9a-a4ae4f48fdab.png)

### Version

0.1.0rc (Default)

### Contribution Guidelines

- [X] I have gone through the contribution guidelines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jay-io** [comment]
We're not ready with the content yet tho. You may proceed if you wish to contribute the write-up as well along with adding it to the HTML.

We are [GirlScript Foundation](https://www.girlscript.tech/home).

[This](https://gsa.bio.link/) is what we do.

**Comment by jay-io** [comment]
@MashyBasker Great! Thank you for taking this up. I'll assign you right away.

**Comment by MashyBasker** [comment]
@KeneePatel Sure. I was unsure of how to proceed in making the content. If you have already thought about then you can take up this issue

**Comment by KeneePatel** [comment]
@MashyBasker Well, I haven't already thought about it, but I guess I will work something out at least. Thanks for passing on the issue.

**Comment by jay-io** [comment]
@KeneePatel Thank you! Go ahead

**Comment by KeneePatel** [comment]
Wait someone already worked out two lines in it. Welp, I guess I will just add something to it as it seems bit small
