### ISSUE TITLE
[Bug]: Font family and Background image

### ISSUE THREAD

**Issue by joyjeetcoding** [gsasansol/GirlScript-Asansol#213]
### Contact Details

joyxbhp6@gmail.com

### What happened?

I want to change the font family.....and want to do a little change in background image linear gradient and a little modifications in navbar too

### Version

0.1.0rc (Default)

### Contribution Guidelines

- [X] I have gone through the contribution guidelines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jay-io** [comment]
@joyjeetcoding Go ahead! Consider using Lato font family. Also, can you try making the heading fonts look like this?

As in "OUR REACH"

![Screenshot from 2022-10-19 17-31-52](https://user-images.githubusercontent.com/55305804/196685181-53e68645-143a-480d-ba08-cc9dacdeaa05.png)

**Comment by joyjeetcoding** [comment]
Here I have used two different font family...One for  the navbar and one for the content part...
I will continue with one of these font family for the headings...
Can I do this ?
![Screenshot (66)](https://user-images.githubusercontent.com/96014361/196716845-13834e04-11d0-4628-8a6a-25d2eab2614c.png)

**Comment by jay-io** [comment]
@joyjeetcoding Cursive typefaces are actually not recommended while building UIs because they are extremely difficult to read. Please use Sans Serif or Serif fonts only ("Lato" as prescribed).

I also wanted to ask if you could establish a font standard throughout. There are several places where fonts aren't Lato and sizes are inconsistent.

**Comment by joyjeetcoding** [comment]
Okay ...no problem I will use Sans serif

**Comment by jay-io** [comment]
@joyjeetcoding We have a few UI fixes. See if you merge them into your progress so far. No worries otherwise.

**Comment by joyjeetcoding** [comment]
Okay... what are the issues? Actually..... I was busy in college works and today I will complete my work and will create the PR :)

**Comment by jay-io** [comment]
@joyjeetcoding You can sync your repo with ours to update your PR with the most recent upgrades and fixes.
