### ISSUE TITLE
Compose an original writeup Document/Roadmap on Introduction to Quantum Bits & Quantum Computing

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#22]
- Write it in either Google Docs or on Ms Word.
- Make sure to add flowcharts/images.
- Share the article link in PR.

**Comment by skar07** [comment]
Please assign this issue to me.

**Comment by Abhinav-J05** [comment]
hey! I would like to contribute in this, please assign this issue to me.
thank you!

**Comment by skar07** [comment]
@jay-io Wanted some clarification regarding the context of the document. Does it need to be an overview of the topic, along with a roadmap outlining the learning path, resources, etc, or does it need to have something else?

**Comment by Nisha213-mar** [comment]
Please Assign this issue to me

**Comment by jay-io** [comment]
**skar07** is already working on it @Nisha213-mar
