### ISSUE TITLE
[Bug] Add content in all the cards of resources

### ISSUE THREAD

**Issue by zugzwang03** [gsasansol/GirlScript-Asansol#229]
### What happened?

A bug happened!
The resources section contains a lot of blog cards, but they are majorly crammed with similar information.  I can add in good content in all of them. Can I make this contribution under Hacktoberfest '22?
![Screenshot_20221024-130911_Chrome](https://user-images.githubusercontent.com/95460021/197473370-4640fceb-f412-4f79-bd2e-38c03c938059.jpg)

### Version

0.1.0rc (Default)

### What browsers are you seeing the problem on?

Chrome

### Contribution Guidelines

- [X] I have gone through the contribution guidelines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jay-io** [comment]
Yes, we kinda have the skeletal design ready (for both the cards and the article container). And the content as well, but we need to set redirects and display the formatted articles via the resource page accordingly (using markdown parsers) depending on what card the user invokes.

This is the task at hand. Are you up for this?

[This is where we're storing the markdown articles.](https://github.com/gsasansol/GirlScript-Asansol/tree/main/components/articles)

Originally we had an idea to compile the metadata as well as the article content [into a JSON](https://github.com/gsasansol/GirlScript-Asansol/issues/21#issuecomment-1264372470) and use the in-built JSON parser to display the content via the resource page. You may do this in a different way if you like but we'll recommend using JSON.

**Comment by zugzwang03** [comment]
Looks like a difficult task for me. I can contribute an article in the already created article directory though. 😃

**Comment by jay-io** [comment]
@zugzwang03 No worries. You can choose an article of your choice and create a feature request for it. We'll assign you on that.

**Comment by jay-io** [comment]
@zugzwang03 Also, I think you can copy and paste the first few lines from the markdown files as a preview to the blog cards. I guess this is what you meant to do previously. You may proceed with either of the issues or both.

**Comment by zugzwang03** [comment]
> @zugzwang03 Also, I think you can copy and paste the first few lines from the markdown files as a preview to the blog cards. I guess this is what you meant to do previously. You may proceed with either of the issues or both.

Yeah let me do it through this issue.

**Comment by zugzwang03** [comment]
> @zugzwang03 No worries. You can choose an article topic of your choice and create a feature request for it. We'll assign you on that.

Let me create a new issue for this.

**Comment by jay-io** [comment]
@zugzwang03 Two issues for you. Let's go
