### ISSUE TITLE
Create a universal blog post page.

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#23]
Sample: [A medium article container](https://nkhilv.medium.com/generating-a-private-rsa-key-for-tests-node-js-c3fc23b3ef1c)

Sample 2: [Refer to the design](https://mondaynote.com/apple-car-bad-idea-after-all-9468947640ee)

1. Must contain legible title, small body text, image attachment provisions
2. Must display GirlScript Asansol Social hyperlinks
3. Must credit the author and editors
4. Anonymous comment section (with options to add Display Name & Email) only the design.

**Comment by modiniraj09** [comment]
Hey GSAsansol Assign it to me to work on.

**Comment by jay-io** [comment]
@modiniraj09 I hope I was clear enough. This page will be invoked with the corresponding content from the article JSONs when we tap on one of the [article cards](https://www.hostinger.es/tutoriales/wp-content/uploads/sites/7/2019/02/jane-friedman.png).
