### ISSUE TITLE
[Feature]  Add an article on Machine Learning

### ISSUE THREAD

**Issue by zugzwang03** [gsasansol/GirlScript-Asansol#230]
### What's on your mind?

Make it shinier!
I want to add an article on machine learning. 

### Contribution Guidelines

- [X] I have gone through the contribution guidelines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jay-io** [comment]
Go ahead!

**Comment by zugzwang03** [comment]
Hey @jay-io , I am facing a problem in this issue. How to obtain the "body" of the json file?

**Comment by jay-io** [comment]
@zugzwang03 [You may use Node's `fs` module](https://github.com/gsasansol/GirlScript-Asansol/issues/21#issuecomment-1264372470). If you're unsure about this, you may leave the body empty:

```json
"body": ""
```

Also, kindly add your article as a blog card, too.

**Comment by zugzwang03** [comment]
Okay thanks 😊
