### ISSUE TITLE
Modify the our teams

### ISSUE THREAD

**Issue by soumali28** [gsasansol/GirlScript-Asansol#234]
changes in the team.html and team.css files
- Add the light and dark mode to the page
- design the cards for the  mobile view
- Change the colour of the text from blue to dark orange.

### Design (for the mobile view only)
 
![Screenshot from 2022-10-26 11-16-10](https://user-images.githubusercontent.com/66300439/197944872-d826825d-dc64-4b51-802e-58c7cbec9a97.png)

**Comment by RanjR219** [comment]
Hi, can I work on the first issue "Add the light and dark mode to the page" ?

**Comment by RanjR219** [comment]
Hi, I would love to work on the card design in the mobile view as well. So can I take that up?

**Comment by soumali28** [comment]
@RanjR219 yeah go ahead its a part of the same issue only.
