### ISSUE TITLE
[Bug] getting rid of some small but surely annoying issues

### ISSUE THREAD

**Issue by KeneePatel** [gsasansol/GirlScript-Asansol#236]
### Contact Details

patelkenee2804@gmail.com

### What happened?

There are following issues and I would like to solve these as well:
- the padding/margining issue in follow us drop down menu
- the uncentered '+' in FAQ's
- the not so compatible 'back to top' button

If you would give me a green to go, I will be able to do it ASAP.

Screenshots:
![image](https://user-images.githubusercontent.com/59523692/198055054-de01a1c6-ac67-4470-974a-1012a9f4e9fa.png)
![image](https://user-images.githubusercontent.com/59523692/198055109-cb880abe-2cc8-4496-a11a-4837faa1681a.png)
![image](https://user-images.githubusercontent.com/59523692/198055217-a8672bd5-c6bd-471b-96d8-ce1faf4fe870.png)

### Version

0.1.0rc (Default)

### Contribution Guidelines

- [X] I have gone through the contribution guidelines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soumali28** [comment]
@KeneePatel Go ahead

**Comment by KeneePatel** [comment]
Allright, thanks for the heads up

**Comment by jay-io** [comment]
@KeneePatel We'd love a simpler Material UI kind of drop down with white background, sans-serif font and proper margins between items and the drop-down box. See if you can achieve something similar:

![dropdown-study-design-shiva](https://user-images.githubusercontent.com/55305804/198086751-1c2762e4-6a16-4023-b5b4-ef8a4164b543.png)

**Comment by KeneePatel** [comment]
@jay-io okay, well I can see what I will be able to do but the main thing I am concerned about is getting the dropdown menu to also follow the theme and that is something I am not so good at lol.

**Comment by jay-io** [comment]
A drop-down dark theme is unnecessary tho. White under all circumstances will do.

**Comment by KeneePatel** [comment]
You kinda misunderstood me with the dark theme. I was referencing to the actual orange like theme and making the dropdown compatible with that. Anyway, I can try that out and see if I will be able to do that and then just make a separate issue for that.

**Comment by jay-io** [comment]
@KeneePatel Oh alright, whatever sails your boat. I was asking if it'd make your work easier to ditch the current drop down theme and build something simpler like in the picture above. If it is indeed easier, you have a green light from us to either do it in this PR or create a separate issue for it.
