### ISSUE TITLE
Compose an original writeup Document/Roadmap on Operating System

### ISSUE THREAD

**Issue by nishkarsh800** [gsasansol/GirlScript-Asansol#24]
- Write it in either Google Docs or on Ms Word
- Make sure to add flowcharts/images.
- Share the article link in PR.

**Comment by nishkarsh800** [comment]
@jay-io Hey project Admin with due love I want to say that, I have created this issue so that I must contribute it to your project. Kindly do assign it to me.

**Comment by jay-io** [comment]
@nishkarsh800 oh sure thing, thanks! Didn't know whether this was a suggestion or a self assignment request.

**Comment by nishkarsh800** [comment]
@jay-io Thanks so much :) It was a kind suggestion. At the end, we all are here to learn and grow.

**Comment by jay-io** [comment]
@modiniraj09 Are you good with writing an article on Linux instead? I'm gonna have to give this to nishkarsh800.

**Comment by modiniraj09** [comment]
@jay-io Ok, I will manage to write on linux

**Comment by jay-io** [comment]
@nishkarsh800 I was in a conversation with other maintainers and we decided we cannot have a broad topic like Operating System as of now. If we decide to have a more concise topic dealing with one of the OSes later, we'll create an issue ourselves, get in touch with you and assign you accordingly. I'll close this issue for now.
