### ISSUE TITLE
Adding Favicons in each Pages and Sub-Pages

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [gsasansol/GirlScript-Asansol#25]
Hey, a site without favicon looks like unprofessional, 
I can add favicon dedicated to girlscript asansol, in each pages and further coming sub-pages.

Please assign this to me

**Comment by girlscript-asansol** [comment]
@Aman-Singh-Kushwaha Thanks for craeting the issue but before creating please discuss with the maintainers and give suggestions to the discord and we'll create the issues accordingly. For now we have a lot of issues already up so surely more issues wll be there.
