### ISSUE TITLE
Adding a preloader to the website 

### ISSUE THREAD

**Issue by YashBawa** [gsasansol/GirlScript-Asansol#26]
A preloader makes the first impression of the website and makes it look much better than blank screen.

**Comment by YashBawa** [comment]
Hey @jay-io please assign me with the issue, as I want to work on it . Also please add the hacktoberfest label. Thanks

**Comment by girlscript-asansol** [comment]
@YashBawa please first discuss the issues with the maintainers in discord and then create it. We already have a lot of issues and and more issues will be there in future.
