### ISSUE TITLE
Create a footer section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#32]
Changes are to be made in index.html, styles.html and index.js files.

### Footer Section should contain:
- GirlScript logo
- All the hyperlinks
- All social media handles of Gs Asansol : [links](https://bio.link/gsa)

### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
![Screenshot from 2022-10-02 10-31-21](https://user-images.githubusercontent.com/104223990/193438693-51ccb142-aa26-46c2-b325-e5de34bb27f5.png)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by heza-ru** [comment]
I would like to work on this issue.

**Comment by Aman-Singh-Kushwaha** [comment]
I have opted to work on this

**Comment by soumali28** [comment]
@heza-ru he suggested  this issue on discord before. You can also suggest some if you want or else wait a few days we'll  create more issues.

**Comment by heza-ru** [comment]
@soumali28 No worries I will wait for other issues that I can take on, always happy to contribute!

**Comment by LalitChauhan27** [comment]
Hey @girlscript-asansol, I will be willing to work on this issue if you have to reassign this.

**Comment by soumali28** [comment]
@Aman-Singh-Kushwaha whats the update?

**Comment by Aman-Singh-Kushwaha** [comment]
I have created proposed basic layout of the footer only waiting to add items in column items like sub pages which I have asked in discord server

**Comment by TheSaptarshiBanerjee** [comment]
I would like to work on this issue.
can you please assign this issue to me?

**Comment by Aman-Singh-Kushwaha** [comment]
@TheSaptarshiBanerjee  I am currently working on it

**Comment by jay-io** [comment]
@Aman-Singh-Kushwaha Please check your GitHub if you haven't yet. There are a few updates in your Footer thread.
