### ISSUE TITLE
Create the our team section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#46]
Changes are to be made in index.html, styles.html and index.js files.

### Our Section should contain:
- Core Team: [Refer to the link to get the details](https://www.linkedin.com/posts/gsasansol_core-members-of-girlscript-asansol-activity-6923232012543668224-AI7q?utm_source=share&utm_medium=member_desktop)
- Volunteers:  [Refer to the link to get the details](https://www.linkedin.com/posts/gsasansol_girlscript-volenteers-activity-6930525848118648832-hbKt?utm_source=share&utm_medium=member_desktop)
- Make sure to add social media links of each team member (linkedIn and Github)
- Our team section is divided into two sub section thats core and volunteers. 
- There will be carousel for the core team and volunteers will be displays in cards 3 in a row.

___
### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
![Screenshot from 2022-10-03 19-00-39](https://user-images.githubusercontent.com/104223990/193590939-130eddc9-a4d3-4ce3-b42b-cbeef914f4f0.png)

![Screenshot from 2022-10-03 19-04-30](https://user-images.githubusercontent.com/104223990/193590998-1e6600cd-3b7d-4eb5-874a-94fb56296620.png)

Links: 
- [Core Inspo](https://girlscript-bhubaneswar.netlify.app/#team)
- [Volunteers Inspo](https://testaeccc.web.app/members)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by AdityaShaw1** [comment]
Assign me pls

**Comment by Anurag-Singh-04** [comment]
Hey @girlscript-asansol I would like to contribute to this project. Please let me know what I can do.

**Comment by Gammashoo** [comment]
Would love to work on this.

**Comment by girlscript-asansol** [comment]
@AdityaShaw1 Whats the update?

**Comment by varun7678** [comment]
I would like to work on that. Please assign me to this

**Comment by qudus2019** [comment]
Can I still work on this ?

**Comment by jay-io** [comment]
@qudus2019 I'm pretty sure there will be things to improve after the first PR on this section. If you're interested in working on the next issue that'll follow, I'll recommend you to join our forums on Discord and starting a thread. Read the contributor guidelines for more information.

**Comment by qudus2019** [comment]
> @qudus2019 I'm pretty sure there will be things to improve after the first PR on this section. If you're interested in working on the next issue that'll follow, I'll recommend you to join our forums on Discord and starting a thread. Read the contributor guidelines for more information.

Alright thank you.... How can I get link to the discord forums

**Comment by jay-io** [comment]
@qudus2019 You're welcome! You'll find everything in the project README.

**Comment by qudus2019** [comment]
> @qudus2019 You're welcome! You'll find everything in the project README.

Thank you once again

**Comment by Debdeep1** [comment]
Any update @varun7678 ?

**Comment by aaheli8** [comment]
Can I be assigned this issue

**Comment by sawan1k** [comment]
I want to work on this issue! assign me:

**Comment by Vic-Dev001** [comment]
Would love to work on this

**Comment by savi001** [comment]
@jay-io can i work on it
