### ISSUE TITLE
Create a FAQ Section

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#47]
Changes are to be made in index.html, styles.html and index.js files.

### FAQ Section should contain:
- What is GS Asansol: GirlScript Asansol is a non-profit student run community registered under the GirlScript Foundation on 23rd April, 2022. We aim to empower people and especially underrepresented groups in the field of technology. GirlScript Asansol's mission is to create opportunity, learning, growth and diversity in technology academia and industry.
- How to join the community: Link to the discord
- Benifits of joining the community:
►  GUIDE & SUPPORT
►  HELP EVERYONE TO LEARN & GROW
►  WORKSHOPS AND MEETING SESSIONS
►  HACKATHONS & INTERNSHIP OPPORTUNITY
___
### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
![Screenshot from 2022-10-03 19-10-51](https://user-images.githubusercontent.com/104223990/193592689-98141549-938a-4606-86c9-49bdb8097cd9.png)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by riyaku11** [comment]
I would like to work on this, please assign me this issue
