### ISSUE TITLE
Revamp resource page (container for blogs #23)

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#48]
- Do a figma design of the resouce page
- it will contain blogs/roadmaps
- refer to issue #23

**Comment by AdityaShaw1** [comment]
Hi admin pls assign me..

**Comment by JASKIRAT11011** [comment]
hi @girlscript-asansol , please assign me the same issue , i can prepare a figma design

**Comment by girlscript-asansol** [comment]
@AdityaShaw1 what's the update?
