### ISSUE TITLE
Compose an original writeup Document/Roadmap on Android Development.

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#49]
- Write it in either Google Docs or on Ms Word.
- Make sure to add flowcharts/images.
- Share the article link in PR.

**Comment by thatsuman** [comment]
Want to work on this.

**Comment by modiniraj09** [comment]
Hey I want to work on it

**Comment by thatsuman** [comment]
With due respect @girlscript-asansol , I was the first one who wished to work on this issue.

**Comment by girlscript-asansol** [comment]
@thatsuman He actually suggested this issue to me.

**Comment by thatsuman** [comment]
Oh Okay! Thanks for clarification. I'll wait for next issue.

**Comment by jay-io** [comment]
@thatsuman You can discuss your own ideas on our Discord issues forum. This way, your chances of being assigned an issue and contributing to this repository will be more. Relying on GitHub notifications will be a rat race.
