### ISSUE TITLE
Fix blog card 

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#53]
- Shift the image to the center
- Give some margin at the bottom of the image
- Style the add comment box a bit.
- Change the post commet button to square.
- Change the background from grey to [this](https://upload.wikimedia.org/wikipedia/commons/2/24/IMG_asnrlyjn.jpg)

**Comment by Subhangi0707** [comment]
i want to work on this issue under hacktober 2022
