### ISSUE TITLE
Make a form for contact us section

### ISSUE THREAD

**Issue by Sukriti-m** [gsasansol/GirlScript-Asansol#55]
I will make a form for contact us section

Please assign this issue to me and add the 'hacktoberfest' label to it. @girlscript-asansol

**Comment by girlscript-asansol** [comment]
@Sukriti-m Thanks for your suggestion, we'll create the issue and assign it to you. You can join the discord to suggest custom issues.

**Comment by girlscript-asansol** [comment]
@Sukriti-m  plz cmt on it 
https://github.com/gsasansol/GirlScript-Asansol/issues/56
