### ISSUE TITLE
Create a Contact Us form

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#56]
Changes are to be made in index.html, styles.html and index.js files.

### Contact Us  Section should contain:
- Title: Contact Us
- Name
- Email
- Message
- Submit Button

___
### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
![Screenshot from 2022-10-04 12-21-33](https://user-images.githubusercontent.com/104223990/193753240-9ae6a276-b977-490c-8a10-e3849cdd561b.png)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by Sukriti-m** [comment]
Please assign this issue to me and add the 'hacktoberfest' label to it. @girlscript-asansol

**Comment by Vic-Dev001** [comment]
@girlscript-asansol, I'll be glad to contribute to this issue

**Comment by Sukriti-m** [comment]
Hey @soumali28 
I apologize that I won't be able to work on this issue. You can go ahead and assign it to somebody else.

**Comment by LalitChauhan27** [comment]
@soumali28 You can assign this to me.

**Comment by Subhajitongit** [comment]
Hey, would love to work on this issue! Can you please assign it to me?

**Comment by TheSaptarshiBanerjee** [comment]
hey , can you assign this issue to me?

**Comment by soumali28** [comment]
@yosaami whats the update?

**Comment by Vic-Dev001** [comment]
@yosaami please can you brief us on the update with the issue assigned to you?

**Comment by jay-io** [comment]
@Vic-Dev001 If you're looking to contribute in our repository, I'll recommend joining the Discord forums and suggesting your own issues. You'll be assigned immediately after approval by the maintainers.

**Comment by yogesh-9999** [comment]
hey @jay-io  Please assign this to me
