### ISSUE TITLE
Create a Navbar

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#6]
### Follow this Guidelines: 
- Theme: [orange,black,white,beige] (Can by any of the two)
- Font: Lato

Changes are to be made in index.html and styles.html files.

### Navbar should contain:
- Logo
- Home
- About Us
- Resources
- Past Events
- Our Team
- FAQ
- Contact Us

### Design 
Inspo: (You can refer to it and can make your own interpretations too, Creativity is welcomed.)
- [Link for the inspo](https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/8f922968919629.5b6dba4c75e8b.png)

### Please join the [Discord](https://discord.com/invite/aVRPbMYfFH) to discuss design of the components.

**Comment by bubblecode76** [comment]
hi i would like to work on this issue

**Comment by girlscript-asansol** [comment]
@bubblecode76 are you a hacktoberfest 2022 contributor? if yes please wait till the contribution period begins we'll assign it to you.

**Comment by bubblecode76** [comment]
yes thank you so much

**Comment by Shivashish-rwt** [comment]
Hey I would like to work in this issue.

**Comment by souravaniket** [comment]
Hey I would also like to work on it.

**Comment by Shashwat0227** [comment]
hey i can add nav bar and even style it perfectly ,  As i have done these things in my hackathon too , you can assign me this

**Comment by arpitasen20** [comment]
Hey, I would like to work on this issue.

**Comment by Sahilbal** [comment]
Hey I would like to work on this issue, I can style it and  even make it a responsive one.

**Comment by Sahilbal** [comment]
@girlscript-asansol  Hey I would like to work on this issue, I can style it and even make it a responsive one.

**Comment by Aman-Singh-Kushwaha** [comment]
Hey i would like work on it i have already applied

**Comment by Nisha213-mar** [comment]
Hey, I am Intrested on this work can you assign it to me

**Comment by soumali28** [comment]
@Aman-Singh-Kushwaha Sorry about that  was kind of busy so forgot abt the earlier issue. We'll  have more issues you cab contribute  to and also cab suggest some in the discord. We'll  assign that to you.

**Comment by minhaj-313** [comment]
Hi, I want to Contribute in Your Project, Can you Please Assign Me for Hactoberfest PR
