### ISSUE TITLE
Create a preloader for the website

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#65]
- You can design your own or take inspiration from the internet.

**Comment by JASKIRAT11011** [comment]
Yes i would like to work on the following issue ,please can u assign me

**Comment by JASKIRAT11011** [comment]
hi @girlscript-asansol ,for the preloader , should i create a figma design for you or a frotnend working code?

**Comment by JASKIRAT11011** [comment]
i have created a branch saying "preloader-added" in my github after forking your repository and further i haveadded the functionality in that branch and sent a PR as well ,
