### ISSUE TITLE
Fix the Navbar 

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#69]
- The navbar in the mobile has some bugs
- The options should be at the bottom and also the logo and brand name should stick together.
![Screenshot from 2022-10-05 11-38-20](https://user-images.githubusercontent.com/104223990/193992831-373853fd-7fce-4e69-99af-b6095dc5fa53.png)

**Comment by LalitChauhan27** [comment]
@girlscript-asansol Please assign this issue to me.
