### ISSUE TITLE
Make the past event section responsive

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#70]
- Currently the past event is nor responsive make it responsive in all devices
- add a shawdow to the carousel items
- add the arrow buttons of the carousel
![Screenshot from 2022-10-05 11-39-13](https://user-images.githubusercontent.com/104223990/193993338-f64cf81d-64d6-4911-b591-4ea2ee0b44fe.png)

**Comment by thatsuman** [comment]
Hey, I would like to work on this

**Comment by Sahilbal** [comment]
I will do that please assign it to me.
