### ISSUE TITLE
Fix the faq sec in the mobile view

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#71]
- add a bit of padding outside the faq boxes. 
- space it out a bit
- also fix the overflow at the y axis
![Screenshot from 2022-10-05 11-48-27](https://user-images.githubusercontent.com/104223990/193993920-29cc1167-6f19-4d97-8cf9-8b23e577f4a9.png)

**Comment by RachitGarg-12** [comment]
Hey @jay-io i would like to work on this issue.

**Comment by jay-io** [comment]
@Debdeep1 #116 Revamped the whole FAQ, so this issue can be closed ig.
