### ISSUE TITLE
Past Event Section Changes

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#72]
- Add clickable links to the cards: Links should redirect to the linkedIn post
- Add 3 cards at a time
- Image allignment
- Add a bit of border radius
- Also the card title, example Portfolio competition change the colour to match the theme.

**Comment by Sahilbal** [comment]
please assign this to me

**Comment by yogesh-9999** [comment]
Hey @girlscript-asansol  assign this to me

**Comment by Sahilbal** [comment]
> Hey @girlscript-asansol assign this to me

I have already submit the work.
