### ISSUE TITLE
Make 404 mobile responsive

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#73]
- Fix the overflow in the 404 page
- Make it mobile responsive
- Increase the image size for the mobile view

**Comment by Subhangi0707** [comment]
please ussign this to me under hacktober fest2022

**Comment by sumit-022** [comment]
I can work on this. Please assign this to me

**Comment by JASKIRAT11011** [comment]
please assign me 404 mobile responsive issue

**Comment by TheSaptarshiBanerjee** [comment]
I can work on this. Please assign this to me
