### ISSUE TITLE
Add a scroll-to-top button

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#76]
Title says it all.

**Comment by Anupamgupt** [comment]
Can I work On this issue?

**Comment by debjitpurohit** [comment]
assing me on that issue

**Comment by jay-io** [comment]
@Anupamgupt @debjitpurohit This issue is assigned to a fellow core member. Follow the `#github` channel on Discord to stay notified for other new issues or suggest your own improvements in the `#custom-issues` forum.

**Comment by aaheli8** [comment]
Please assign me this issue.

**Comment by Noobham** [comment]
hey , Can you plzz assign this issue to me . i want to work on it .

**Comment by TheSaptarshiBanerjee** [comment]
please assign this issue to me. I am excited to work on it.

**Comment by aaheli8** [comment]
Working on this issue
