### ISSUE TITLE
Dismissable top notification bar with mutable content

### ISSUE THREAD

**Issue by jay-io** [gsasansol/GirlScript-Asansol#78]
- Notif. bar must be versatile with these properties defined:
  - background color
  - smooth collapse transition
  - a notif-bar-btn class with tunable background and text: hover, on-click effects (Material UI recommended)
  - center alignment of all content other than the dismissing cross on the extreme right (appropriate margins please)

Inspo:
![Random google image](https://themaverickspirit.com/wp-content/uploads/2020/08/moosend-web-alert-bar.png)

PS: form field not required

**Comment by Rahul-Palahwat** [comment]
Hey @jay-io i want to work on this issue , can you assign this to me??
