### ISSUE TITLE
Theme change button doesn't work

### ISSUE THREAD

**Issue by ahmedsilat44** [gsasansol/GirlScript-Asansol#80]
The Theme change button on the NavBar has no functionality 
![image](https://user-images.githubusercontent.com/105588821/194035160-9a76ce3a-96af-415c-9922-cfa5bf297d76.png)

**Comment by RachitGarg-12** [comment]
Hey @ahmedsilat44 can i work on this issue

**Comment by ahmedsilat44** [comment]
> Hey @ahmedsilat44 can i work on this issue

I am not a maintainer I just saw this bug and raised the issue

**Comment by RachitGarg-12** [comment]
Ok

**Comment by ahmedsilat44** [comment]
> @ahmedsilat44 the dark mode does work but not the header sphere part if you want to fix that then we'll create the issue for you. For futher suggestions you can suggest the custom issue on our discord and we'll create it

I am not sure how to fix this. If you can guide me through it I would like to contribute.

**Comment by girlscript-asansol** [comment]
yeah sure we'll guide you. In the header section there is the curve spere which is not responsive to the dark mode. you just have to select it and add class name dark to it. If you want to contribute then we'll create the issue.

**Comment by ahmedsilat44** [comment]
> yeah sure we'll guide you. In the header section there is the curve spere which is not responsive to the dark mode. you just have to select it and add class name dark to it. If you want to contribute then we'll create the issue.

Thank you for the guide, and yes I would like to contribute. 😃
