### ISSUE TITLE
Add links to the navbar

### ISSUE THREAD

**Issue by girlscript-asansol** [gsasansol/GirlScript-Asansol#82]
- redirect the navbar to the proper links when clicked on it.

**Comment by LalitChauhan27** [comment]
@girlscript-asansol Can I work on this issue?

**Comment by Rahul-Palahwat** [comment]
Hey @girlscript-asansol please assign this issue to me??

**Comment by debjitpurohit** [comment]
Assing me this issue.

**Comment by girlscript-asansol** [comment]
@Rahul-Palahwat he suggested this issue on your discord. you can wait for new issues or can suggest some too on our discord server.

**Comment by sumit-022** [comment]
I can work in this. Please assign me the issue

**Comment by Ashpreetwadhwa** [comment]
I want to do this task can you assign me this
