### ISSUE TITLE
(1) Material UI for notification bar button class, (2) centre alignment for notif bar components

### ISSUE THREAD

**Issue by regdocs** [gsasansol/GirlScript-Asansol#97]
- Centre all components in the notif. bar. The button looks edgy. Redefine the css to resemble google's Material UI:

![Screenshot from 2022-10-05 22-53-45](https://user-images.githubusercontent.com/55305804/194124051-44b6d8d4-2d71-4d8c-bc5c-74cbd1f55d26.png)

Material UI button (choose primary):

![1cfbjlepc41xy7f4tccp](https://user-images.githubusercontent.com/55305804/194124270-faf6f01f-c022-4240-ae44-10eb908a189b.png)

- Change bar's background to `#00111c`
- & Button colour to `#737df1`
- Text can remain white

**Comment by jay-io** [comment]
@LalitChauhan27 sure.

**Comment by LalitChauhan27** [comment]
@jay-io Can you please add the necessary labels.

**Comment by jay-io** [comment]
@LalitChauhan27 Can you try adding a smooth collapse animation as well?

**Comment by LalitChauhan27** [comment]
> @LalitChauhan27 Can you try adding a smooth collapse animation as well?

Okay, no problem.

**Comment by LalitChauhan27** [comment]
Hey @jay-io, I don't get any resource until now from where I can use google's Material UI buttons in our css file. They all are implemented in java language for andriod apps. Can you please refer me to some resources or you can review the changes I have made until now, from now on I just need to add a smooth collapse animation.

**Comment by LalitChauhan27** [comment]
> @LalitChauhan27 [Here you go.](https://getcssscan.com/css-buttons-examples) `Button 61`. Keep this on your bookmarks... will always come handy. I think the content is still a little misaligned. Why don't you use a centred div to contain the text and the button?

Thanks for the help. I used the div that contains only the text and the button to center the elements. Can you please explain what is missing?

**Comment by jay-io** [comment]
@LalitChauhan27 Let's look at the code in your PR, if you're done.
